services:
  - type: web
    name: bitespeed-api
    runtime: docker
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: DATABASE_URL
        value: jdbc:postgresql://dpg-d1mnouer433s73dinh3g-a.oregon-postgres.render.com:5432/bitespeed_36km
      - key: DATABASE_USERNAME
        value: bitespeed_36km_user
      - key: DATABASE_PASSWORD
        value: VafGLQZ8nA0jlrZeRGoc9lt8As7RDLGA
      - key: PORT
        value: 8080
    healthCheckPath: /actuator/health
    autoDeploy: true