services:
  - type: web
    name: bitespeed-api
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bitespeed-db
          property: connectionString
    healthCheckPath: /actuator/health