services:
  - type: web
    name: bitespeed-api
    runtime: docker
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/*.jar
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bitespeed-db
          property: connectionString
    healthCheckPath: /actuator/health